<a href="https://colab.research.google.com/github/gbiamgaurav/Mathematics-for-ML/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Dot Product

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
x = np.array([2,3,5])

In [3]:
x

array([2, 3, 5])

In [4]:
xpt = torch.tensor([2,3,5.])
xtf = tf.Variable([2,3,5.])

In [5]:
y = x+1
y

array([3, 4, 6])

In [6]:
np.dot(x,y)

48

In [7]:
2*3+3*4+5*6

48

In [8]:
ypt = torch.tensor([9,6,5.])
ypt

tensor([9., 6., 5.])

In [9]:
xpt

tensor([2., 3., 5.])

In [10]:
torch.dot(xpt, ypt)

tensor(61.)

In [11]:
ytf = tf.Variable([9,6,5.])
ytf

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([9., 6., 5.], dtype=float32)>

In [12]:
xtf

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 3., 5.], dtype=float32)>

In [13]:
tf.reduce_sum(tf.multiply(xtf, ytf))

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>

In [14]:
tf.tensordot(xtf, ytf, 1)

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>

### Orthogonal Vectors

In [15]:
i = np.array([1,0])
i

array([1, 0])

In [16]:
j = np.array([0,1])
j

array([0, 1])

In [17]:
np.dot(i,j)

0