<a href="https://colab.research.google.com/github/gbiamgaurav/Mathematics-for-ML/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Dot Product

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
x = np.array([2,3,5])

In [3]:
x

array([2, 3, 5])

In [4]:
xpt = torch.tensor([2,3,5.])
xtf = tf.Variable([2,3,5.])

In [5]:
y = x+1
y

array([3, 4, 6])

In [6]:
np.dot(x,y)

48

In [7]:
2*3+3*4+5*6

48

In [8]:
ypt = torch.tensor([9,6,5.])
ypt

tensor([9., 6., 5.])

In [9]:
xpt

tensor([2., 3., 5.])

In [10]:
torch.dot(xpt, ypt)

tensor(61.)

In [11]:
ytf = tf.Variable([9,6,5.])
ytf

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([9., 6., 5.], dtype=float32)>

In [12]:
xtf

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 3., 5.], dtype=float32)>

In [13]:
tf.reduce_sum(tf.multiply(xtf, ytf))

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>

In [14]:
tf.tensordot(xtf, ytf, 1)

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>

### Orthogonal Vectors

In [15]:
i = np.array([1,0])
i

array([1, 0])

In [16]:
j = np.array([0,1])
j

array([0, 1])

In [17]:
np.dot(i,j)

0

### Transposition

In [18]:
import numpy as np
import torch
import tensorflow as tf


In [19]:
x = np.array([[2,3,5],[9,6,8]])
x

array([[2, 3, 5],
       [9, 6, 8]])

In [20]:
x.T

array([[2, 9],
       [3, 6],
       [5, 8]])

In [21]:
xpt = torch.tensor([[2,3,5.],[9,6,8.]])
xpt

tensor([[2., 3., 5.],
        [9., 6., 8.]])

In [22]:
xpt.T

tensor([[2., 9.],
        [3., 6.],
        [5., 8.]])

In [23]:
xtf = tf.Variable([[2,3,5.],[9,6,8.]])
xtf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 5.],
       [9., 6., 8.]], dtype=float32)>

In [24]:
tf.transpose(xtf)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 9.],
       [3., 6.],
       [5., 8.]], dtype=float32)>

### Arithmetic Operations

In [25]:
x = np.array([[2,3,5],[9,6,8]])
xpt = torch.tensor([[2,3,5.],[9,6,8.]])
xtf = tf.Variable([[2,3,5.],[9,6,8.]])

In [26]:
x

array([[2, 3, 5],
       [9, 6, 8]])

In [27]:
xpt

tensor([[2., 3., 5.],
        [9., 6., 8.]])

In [28]:
xtf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 5.],
       [9., 6., 8.]], dtype=float32)>

In [29]:
x*2

array([[ 4,  6, 10],
       [18, 12, 16]])

In [30]:
x+2

array([[ 4,  5,  7],
       [11,  8, 10]])

In [31]:
xpt*2

tensor([[ 4.,  6., 10.],
        [18., 12., 16.]])

In [32]:
xtf*2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  6., 10.],
       [18., 12., 16.]], dtype=float32)>

In [34]:
xpt + 2

tensor([[ 4.,  5.,  7.],
        [11.,  8., 10.]])

In [33]:
torch.add(xpt, 2)

tensor([[ 4.,  5.,  7.],
        [11.,  8., 10.]])

In [35]:
xtf + 2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  5.,  7.],
       [11.,  8., 10.]], dtype=float32)>

In [36]:
tf.add(xtf, 2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  5.,  7.],
       [11.,  8., 10.]], dtype=float32)>

In [37]:
xpt*2

tensor([[ 4.,  6., 10.],
        [18., 12., 16.]])

In [38]:
torch.mul(xpt, 2)

tensor([[ 4.,  6., 10.],
        [18., 12., 16.]])

In [39]:
xtf*2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  6., 10.],
       [18., 12., 16.]], dtype=float32)>

In [40]:
tf.multiply(xtf, 2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  6., 10.],
       [18., 12., 16.]], dtype=float32)>

### Hadamard Operations

Element wise operations on matrices of same order

In [41]:
x = np.array([[2,3,5],[9,6,8]])
xpt = torch.tensor([[2,3,5.],[9,6,8.]])
xtf = tf.Variable([[2,3,5.],[9,6,8.]])

In [42]:
x

array([[2, 3, 5],
       [9, 6, 8]])

In [43]:
xpt

tensor([[2., 3., 5.],
        [9., 6., 8.]])

In [44]:
xtf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 5.],
       [9., 6., 8.]], dtype=float32)>

In [45]:
y = x+4
y

array([[ 6,  7,  9],
       [13, 10, 12]])

In [47]:
x

array([[2, 3, 5],
       [9, 6, 8]])

In [46]:
x+y

array([[ 8, 10, 14],
       [22, 16, 20]])

In [48]:
x*y

array([[ 12,  21,  45],
       [117,  60,  96]])

In [49]:
y/x

array([[3.        , 2.33333333, 1.8       ],
       [1.44444444, 1.66666667, 1.5       ]])

In [50]:
ypt = torch.add(xpt, 2)
ypt

tensor([[ 4.,  5.,  7.],
        [11.,  8., 10.]])

In [51]:
xpt

tensor([[2., 3., 5.],
        [9., 6., 8.]])

In [52]:
xpt+ypt

tensor([[ 6.,  8., 12.],
        [20., 14., 18.]])

In [53]:
ypt/xpt

tensor([[2.0000, 1.6667, 1.4000],
        [1.2222, 1.3333, 1.2500]])

In [54]:
ypt*xpt

tensor([[ 8., 15., 35.],
        [99., 48., 80.]])

### Reduction

In [55]:
x = np.array([[2,3,5],[9,6,8]])
xpt = torch.tensor([[2,3,5.],[9,6,8.]])
xtf = tf.Variable([[2,3,5.],[9,6,8.]])

In [56]:
x

array([[2, 3, 5],
       [9, 6, 8]])

In [57]:
xpt

tensor([[2., 3., 5.],
        [9., 6., 8.]])

In [58]:
xtf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 5.],
       [9., 6., 8.]], dtype=float32)>

In [59]:
x.sum()

33

In [61]:
torch.sum(xpt)

tensor(33.)

In [62]:
tf.reduce_sum(xtf)

<tf.Tensor: shape=(), dtype=float32, numpy=33.0>

In [64]:
x

array([[2, 3, 5],
       [9, 6, 8]])

In [66]:
x.sum(axis=0)

array([11,  9, 13])

In [67]:
x.sum(axis=1)

array([10, 23])

In [68]:
torch.sum(xpt, 0)

tensor([11.,  9., 13.])

In [69]:
torch.sum(xpt, 1)

tensor([10., 23.])

In [70]:
tf.reduce_sum(xtf, 0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([11.,  9., 13.], dtype=float32)>

In [71]:
tf.reduce_sum(xtf, 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 23.], dtype=float32)>

In [72]:
x

array([[2, 3, 5],
       [9, 6, 8]])

In [73]:
x.min()

2

In [74]:
torch.min(xpt)

tensor(2.)

In [75]:
tf.reduce_min(xtf)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>